runner:
  bandit:
    cmd:  cat ./bandit.txt
    errorformat: # (optional if you use `format`)
      - "%f:%l:%c:%m" 
    name: bandit # (optional. you can overwrite <tool-name> defined by runner key)
    level: info # (optional. same as -level flag. [info,warning,error])
  pep8:
    cmd: cat ./pep8.txt
    format: pep8
  hadolint:
    cmd: cat ./hadolint.txt
    format: rdjson
    level: error # (optional. same as -level flag. [info,warning,error])
  shellcheck:
    cmd: cat ./shellcheck.txt
    format: "%f:%l:%c:%m %n" 
    level: warning # (optional. same as -level flag. [info,warning,error])
