name: Reviewdog_rev2

# read-write repo token
# access to secrets
on: [ pull_request ]
#   workflow_run:
#     workflows: [Scans]
#     types:
#       - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1.0.4
        
      - name: 'Download artifact'
        uses: actions/github-script@v6.4.1
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "scan_results"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/scan_results.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip scan_results.zip
    
      - name: Display structure of downloaded files
        run: ls -R
        
      - name: Run Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWDOG_FAIL_ON_ERROR: 'true'
        run: |
          reviewdog -conf .reviewdog.yml -fail-on-error=$REVIEWDOG_FAIL_ON_ERROR -reporter=github-pr-check
