name: Reviewdog_rev2

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Scans"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: bandit_results
    
      - name: Display structure of downloaded files
        run: ls -R
      
      - run: unzip bandit_results.zip
      - name: Run Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -conf .reviewdog.yml -fail-on-error=$REVIEWDOG_FAIL_ON_ERROR -reporter=github-pr-check
