name: Scans
on: [pull_request]
jobs:
  bandit:
    name: runner / bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bandit
        run: |
          pip install bandit
      - name: Run and save results 
        run: |
          mkdir -p ./bandit_results
          cp .reviewdog.yml ./bandit_results
          bandit -r ./ -o ./bandit_results/bandit.txt --exit-zero -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}"
        
      - uses: actions/upload-artifact@v3
        with:
          name: bandit_results
          path: ./bandit_results/
  
  reviewdog:
    runs-on: ubuntu-latest
    needs: bandit
    steps:
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1.0.4
        
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: bandit_results
    
      - name: Display structure of downloaded files
        run: ls -R && echo ${{github.workspace}}
    
      - name: Run Reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEWDOG_FAIL_ON_ERROR: 'true'
        run: |
          reviewdog -conf .reviewdog.yml -fail-on-error=$REVIEWDOG_FAIL_ON_ERROR -reporter=github-pr-check
