name: Scans
on: [pull_request]
jobs:
  bandit:
    name: runner / bandit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install bandit
        run: |
          pip install bandit
      - name: Run and save results 
        run: |
          mkdir -p ./bandit_results
          bandit -r ./ -o bandit.txt --exit-zero -f custom --msg-template "{relpath}:{line}:{col}:{test_id}:{severity}:{msg}"
        
      - uses: actions/upload-artifact@v3
        with:
          name: bandit_results
          path: ./bandit_results/
